server: 
  port: 7070
  address: localhost
  session:
    timeout: 600
  contextPath: /rujianbin-provider
#http://127.0.0.1:54000/health  check health
management:
  port: 54000
  security:
        enabled: false
spring: 
  profiles:
    active: dev


    
    
    
    
    