server: 
  port: 7070
  address: localhost
  session:
    timeout: 35
  contextPath: /rujianbin-provider
management:
  port: 54000
spring: 
  profiles:
    active: dev

    
    
    
    
    