dubbo:
  application:
    name: rujianbin-provider
  registry:
    address: zookeeper://192.168.110.58:2181
    group: rjb
    file: /data/rujianbin-provider/registry.properties
  protocol:
    name: rest
    port: 7777
    server: tomcat
    threads: 500
    accepts: 100

spring: 
  redis: 
    cluster:
      max-redirects: 10
      nodes: 10.5.4.155:7000,10.5.4.155:7001,10.5.4.155:7002,10.5.4.155:7003,10.5.4.155:7004,10.5.4.155:7005
    timeout: 30000
    pool:
      max-idle: 20
      min-idle: 10
      max-active: 1000
      max-wait: -1
  cache:
    type: REDIS
    cache-names: namespace1,namespace2,namespace3
  session: 
    store-type: REDIS
  http: 
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.91.228:3322/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  data:
    mongodb:
      uri: mongodb://192.168.91.228:27015/testdb
  freemarker:
    variables:
      static: http://127.0.0.1/static/
      jsVersion: 1.0.0
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/template/freemarker/
    settings:
      template_update_delay: 0
    
mybatis:
  typeAliasesPackage: com.rujianbin.provider.mybatis.entity
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    mapUnderscoreToCamelCase: true
    defaultStatementTimeout: 25000
    defaultExecutorType: REUSE
    useGeneratedKeys: true
